### ISSUE TITLE
Scope the problem and identify the reasons why it has happended

### ISSUE THREAD

**Issue by uon-rcking** [99904047/DM2-Allocated-AR-ledger-payments-not-shown-on-payment-plan-table#1]
TBC

**Comment by 99904047** [comment]
We have compared rest amount held on asutrans with the grouped value held on acrpayplan for rest_cur and identified adround 80 lines in which the payment is on asutrans not on acrpayplan. Also we have an additional 40 lines held on asuhistr as the invoice has been fully paid but acrpayplan still shows lines outstanding.

Action required -
1 - Categorise the journal types within these errors
2 - Understand how this has happened by replicating within the test environment

**Comment by 99904047** [comment]
This problem is bigger than first thought and therefore have increased the points score to a sprint week. I have also agreed to document the proposed problem and solution to correct the acrpayplan table to reflect acutrans plus acuhistr to UNIT4 for agreement in terms of the fix.

**Comment by 99904047** [comment]
This task has been broken down to the following sub tasks:

1 - Difference identification between (acutrans plus acuhistr vs acrpayplan)
2 - Explaination for differences
3 - Proposed resolutions / training
4 - Confirmation of when acrpayplan does and doesn't get updated as well as agreement on proposed correction process to acrpayplan with UNIT4
5 - Alert identification of future mis-matches
6 - Resolution of problems within test and UAT
7 - Training rollout if needed
8 - Resolution within LIVE

**Comment by 99904047** [comment]
Task broken down
