### ISSUE TITLE
Please run the SQL script again using acuhistr

### ISSUE THREAD

**Issue by 99904047** [99904047/DM2-Allocated-AR-ledger-payments-not-shown-on-payment-plan-table#5]
Debbie

Can you run this SQL again this time replacing acutrans with acuhistr?

**Comment by uon-djlegg** [comment]
SQL run with tablename replaced ACUHISTR.    Results emailed to Martin

**Comment by 99904047** [comment]
Data provided

SELECT acu.[apar_id]
, acu.voucher_type
,acu.[rest_amount] 
,(select sum(acr.rest_curr)
from [dbo].[acrpayplan] acr
where acr.apar_id = acu.apar_id
and acr.voucher_no = acu.voucher_no
and acr.client = acu.client
and acr.sequence_no = acu.sequence_no
group by acr.[apar_id]
,acr.[sequence_no]
,acr.[voucher_no]
) 
as rest_curr
,acu.[sequence_no]
,acu.[voucher_no]
FROM dbo.acuhistr acu
where acu.client = 'NU'
and acu.currency = 'GBP'
and acu.[rest_amount] <> 
(select sum(acr.rest_curr)
from [dbo].[acrpayplan] acr
where acr.apar_id = acu.apar_id
and acr.voucher_no = acu.voucher_no
and acr.client = acu.client
and acr.sequence_no = acu.sequence_no
group by acr.[apar_id]
,acr.[sequence_no]
,acr.[voucher_no]
,acr.[client]
)
