### ISSUE TITLE
 4 - Confirmation of when acrpayplan does and doesn't get updated as well as agreement on proposed correction process to acrpayplan with UNIT4

### ISSUE THREAD

**Issue by 99904047** [99904047/DM2-Allocated-AR-ledger-payments-not-shown-on-payment-plan-table#8]

**Comment by 99904047** [comment]
Emailed Janet Baines today the follow

We have undertaken a reconciliation of rest_amount values within acutrans against rest_curr on acrpayplan, of the 10,000 invoices on acutrans around 100 odd cash receipts are missing on acrpayplan. Do only certain treatment codes work in terms of matching cash receipts to invoices against the payment plan table? Do you know of any reason why the payment plan table would not be updated but the acutrans table would be?

**Comment by uon-jbaine** [comment]
Martin I'm really Not Sure.  I know not all Students will Have Payment PLans Applied Prior to INvoicing as thi was a manual process so could this have something to do with it?
